
GET http://localhost:4000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsIm11dGF0ZVBheWxvYWQiOnRydWUsImlhdCI6MTU4OTgyMTIxNiwiZXhwIjoxNTg5ODIxMjQ2fQ.VPB8-Gvp6_482HV3c6goLM8jqvBCLDLdIpqMyVyWzn0

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODA0Nzk5MDYsImV4cCI6MTU4MDQ3OTkyNn0.z_NSbhDqqhjzwW3YQPyd_UKHJtY2u69kMdEzUih-XmY",
  "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTgwNDcyNzMxfQ.zCFoV1uIOTlymN4E3u9TlSZbuigHI9UAtpnGyX3DhsU"
}

###

// get new access token by passing refresh token 
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTU4OTgyMTA0MCwiZXhwIjoxNTg5ODIxMDUxfQ.P8Oya4paQhqml525oqvfx1IwZ3amT6elsHzA57BqtUo"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}